targetScope = 'subscription'

@minLength(1)
@maxLength(64)
@description('Name of the environment that can be used as part of naming resource convention')
param environmentName string

@minLength(1)
@description('Primary location for all resources')
param location string

@description('Primary location for all resources')
param DeploymentTimeStamp string = utcNow('d')

@description('Id of the user or app to assign application roles')
// param principalId string = ''
param storageAccountName string = ''

// Tags that should be applied to all resources.
// 
// Note that 'azd-service-name' tags should be applied separately to service host resources.
// Example usage:
//   tags: union(tags, { 'azd-service-name': <service name in azure.yaml> })
var tags = {
  'azd-env-name': environmentName
  CreatedBy: 'CreatorUserName' // ToDo: Replace with actual creator name
  CreatedDate: DeploymentTimeStamp // ToDo: Update format specifier if needed (https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#table-of-format-specifiers)
  Project: 'SRE'
  Purpose: 'File Transfer'
}

#disable-next-line no-unused-vars
var abbrevs = loadJsonContent('./abbreviations.json')

// Generate a unique token to be used in naming resources.
// Remove linter suppression after using.
#disable-next-line no-unused-vars
var resourceToken = toLower(uniqueString(subscription().id, environmentName, location))

var stAcctName = !empty(storageAccountName) ? storageAccountName : '${abbrevs.storageStorageAccounts}${resourceToken}'

// Add resources to be provisioned below.
// A full example that leverages azd bicep modules can be seen in the todo-python-mongo template:
// https://github.com/Azure-Samples/todo-python-mongo/tree/main/infra

// Organize resources in a resource group
resource rg 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: 'rg-${environmentName}'
  location: location
  tags: tags
}

// Create a storage account
module storage './core/storage/storage-account.bicep' = {
  name: 'storage'
  scope: rg
  params: {
    name: stAcctName
    location: location
    tags: tags
    containers: [
      {
        name: 'default'
      }
      {
        name: 'pii-sample-unstructured'
      }
    ]
  }
}

// Create a cognitive account
module cognitiveAccount './core/ai/cognitiveAccount.bicep' = {
  name: 'cognitiveAccount'
  scope: rg
  params: {
    name: '${abbrevs.cognitiveServicesAccounts}${resourceToken}'
    location: location
    tags: tags
  }
}

// Create a search service
module searchService './core/ai/searchService.bicep' = {
  name: 'searchService'
  scope: rg
  params: {
    searchServiceName: '${abbrevs.searchSearchServices}${resourceToken}'
    searchSkuName: 'standard'
    location: location
    tags: tags
  }
}

// Create a cosmos db account
module cosmosDb './core/db/cosmosAccount.bicep' = {
  name: 'cosmosDb'
  scope: rg
  params: {
    // name: '${abbrevs.cosmosDatabaseAccounts}${resourceToken}' // remove incorrect, Generated by GHCP
    name: '${abbrevs.documentDBDatabaseAccounts}${resourceToken}'
    location: location
    tags: tags
    kind: 'GlobalDocumentDB'
  }
}

// Create a cosmos db SQL database
module cosmosSqlDatabase './core/db/cosmosSqlDatabase.bicep' = {
  name: 'cosmosSqlDatabase'
  scope: rg
  params: {
    accountName: cosmosDb.outputs.cosmosDbName
    location: location
    databaseName: 'deid'
    throughput: 1000
  }

}

// Create a cosmos db SQL container
module cosmosSqlContainer './core/db/cosmosSqlContainer.bicep' = {
  name: 'cosmosSqlContainer'
  scope: rg
  params: {
    accountName: cosmosDb.outputs.cosmosDbName
    databaseName: 'deid'
    containerName: 'metadata'
    partitionKeyPath: '/Uri'
    location: location
  }
  dependsOn: [
    cosmosSqlDatabase
  ]
}

// Create an app service plan
module appServicePlan './core/db/appServicePlan.bicep' = {
  name: 'appServicePlan'
  scope: rg
  params: {
    name: 'plan1'
    location: location
    skuName: 'S1'
  }
}

// Create a second app service plan
module appServicePlan2 './core/db/appServicePlan.bicep' = {
  name: 'appServicePlan2'
  scope: rg
  params: {
    name: 'plan2'
    location: location
    skuName: 'S1'
  }
}

// Create a function app
module functionApp './core/web/functionApp.bicep' = {
  name: 'functionApp'
  scope: rg
  params: {
    functionAppName: '${abbrevs.webSitesFunctions}${resourceToken}'
    // osType: 'Windows'
    runtime: 'dotnet-isolated'
    // roleAssignmentScope: storage //.outputs.storageObjectSymbolic
    storageAccountName: storage.outputs.storageAccountName
    appServicePlanName: appServicePlan.outputs.appServicePlanName
    location: location
    tags: union(tags, { 'azd-service-name': 'custom-skills' })
    openAiEndpoint: aoai.outputs.aoaiEndpoint
    openAiDeploymentName: aoai.outputs.gpt4oMiniDeploymentName
    openAiApiKey: aoai.outputs.aoaiApiKey
  }
}

// Create a web app
module webApp './core/web/webApp.bicep' = {
  name: 'webApp'
  scope: rg
  params: {
    webAppName: '${abbrevs.webSitesAppService}${resourceToken}'
    runtime: 'DOTNET|8.0'
    appServicePlanName: appServicePlan2.outputs.appServicePlanName
    location: location
    tags: union(tags, { 'azd-service-name': 'mvc' })
    cosmosEndpoint: cosmosDb.outputs.cosmosDbEndpoint
    searchServiceEndpoint: searchService.outputs.searchServiceEndpoint
    searchServiceApiKey: searchService.outputs.searchServiceApiKey
    storageAccountEndpoint: storage.outputs.storageAccountEndpoint
    storageAccountName: storage.outputs.storageAccountName
  }
}

// Create an Azure OpenAI resource
module aoai './core/ai/aoai.bicep' = {
  name: 'aoai'
  scope: rg
  params: {
    aoaiName: 'aoai-${resourceToken}'
    location: location
    tags: tags
  }
}

module storageBlobContributorRoleAssignmentFunctionApp './core/security/roleAssignment.bicep' = {
  name: 'storageBlobContributorRoleAssignmentFunctionApp'
  scope: rg
  params: {
    principalId: functionApp.outputs.functionAppPrincipalId
    roleDefinitionId: 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'
    targetResourceId: storage.outputs.storageAccountId
  }
}

module storageBlobContributorRoleAssignmentWebApp './core/security/roleAssignment.bicep' = {
  name: 'storageBlobContributorRoleAssignmentWebApp'
  scope: rg
  params: {
    principalId: webApp.outputs.webAppPrincipalId
    roleDefinitionId: 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'
    targetResourceId: storage.outputs.storageAccountId
  }
}

// Note: Cosmos DB SQL role assignments need to be created post-deployment using az cosmosdb sql role assignment create
// This is because Cosmos DB uses custom role definitions that are not standard Azure RBAC roles

output AZURE_LOCATION string = location
output AZURE_TENANT_ID string = subscription().tenantId
output AZURE_SUBSCRIPTION_ID string = subscription().subscriptionId
output AZURE_RESOURCE_GROUP string = rg.name
output AZURE_STORAGE_ACCOUNT_NAME string = storage.outputs.storageAccountName
output AZURE_COSMOS_ENDPOINT string = cosmosDb.outputs.cosmosDbEndpoint
output AZURE_SEARCH_SERVICE_ENDPOINT string = searchService.outputs.searchServiceEndpoint
output AZURE_SEARCH_SERVICE_API_KEY string = searchService.outputs.searchServiceApiKey
output AZURE_FUNCTION_APP_NAME string = functionApp.outputs.functionAppName
output AZURE_WEB_APP_NAME string = webApp.outputs.webAppName
output AZURE_OPENAI_ENDPOINT string = aoai.outputs.aoaiEndpoint
output AZURE_COGNITIVE_SERVICES_ENDPOINT string = cognitiveAccount.outputs.cognitiveAccountEndpoint
output AZURE_FUNCTION_APP_ENDPOINT string = 'https://${functionApp.outputs.functionAppName}.azurewebsites.net'
output AZURE_STORAGE_ACCOUNT_ENDPOINT string = storage.outputs.storageAccountEndpoint
output AZURE_STORAGE_ACCOUNT_ID string = storage.outputs.storageAccountId
